spring:
  datasource:
    url: jdbc:mysql://120.79.84.251:3306/bookPurchase?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: lhx19960303
  thymeleaf:
    #禁止thymeleaf缓存（建议：开发环境设置为false，生成环境设置为true）
    cache: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# MyBatis
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.engineering.bookpurchase
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mapper/mybatis-config.xml
logging:
  level:
    com.guoet.lanchong:
      debug

